// this defines the type of data that will be sent/received

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/event.proto

// protobuf namesapce (avoids name conflicts, package1.name vs package2.name)

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestionService_SendEvent_FullMethodName = "/aegis.EventIngestionService/SendEvent"
)

// EventIngestionServiceClient is the client API for EventIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// defines the gRPC service and its method(s)
type EventIngestionServiceClient interface {
	// the method takes an Event message and returns an Ack message
	SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Ack, error)
}

type eventIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionServiceClient(cc grpc.ClientConnInterface) EventIngestionServiceClient {
	return &eventIngestionServiceClient{cc}
}

func (c *eventIngestionServiceClient) SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, EventIngestionService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngestionServiceServer is the server API for EventIngestionService service.
// All implementations must embed UnimplementedEventIngestionServiceServer
// for forward compatibility.
//
// defines the gRPC service and its method(s)
type EventIngestionServiceServer interface {
	// the method takes an Event message and returns an Ack message
	SendEvent(context.Context, *Event) (*Ack, error)
	mustEmbedUnimplementedEventIngestionServiceServer()
}

// UnimplementedEventIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServiceServer struct{}

func (UnimplementedEventIngestionServiceServer) SendEvent(context.Context, *Event) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventIngestionServiceServer) mustEmbedUnimplementedEventIngestionServiceServer() {}
func (UnimplementedEventIngestionServiceServer) testEmbeddedByValue()                               {}

// UnsafeEventIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServiceServer will
// result in compilation errors.
type UnsafeEventIngestionServiceServer interface {
	mustEmbedUnimplementedEventIngestionServiceServer()
}

func RegisterEventIngestionServiceServer(s grpc.ServiceRegistrar, srv EventIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestionService_ServiceDesc, srv)
}

func _EventIngestionService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).SendEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngestionService_ServiceDesc is the grpc.ServiceDesc for EventIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.EventIngestionService",
	HandlerType: (*EventIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventIngestionService_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/event.proto",
}
